on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Install packages to build it
        run: |
          sudo apt install cmake build-essential binutils-arm-none-eabi

      - name: Clone the repository
        uses: actions/checkout@v5

      - name: Build and run each test
        run: |
          sh scripts/runtests.sh
